#!/bin/bash
CIDdir=/etc/CAT-BOT && [[ ! -d ${CIDdir} ]] && mkdir ${CIDdir}
DIRSCRIPT=/etc/cat/script && [[ ! -d ${DIRSCRIPT} ]] && mkdir -p ${DIRSCRIPT}
DIR="/etc/http-shell"
IVAR="/etc/http-instas"
bar="\e[0;31m=====================================================\e[0m"

msg() {
    BRAN='\033[1;37m' && VERMELHO='\e[31m' && VERDE='\e[32m' && AMARELO='\e[33m'
    AZUL='\e[34m' && MAGENTA='\e[35m' && MAG='\033[1;36m' && NEGRITO='\e[1m' && SEMCOR='\e[0m'
    case $1 in
    -ne) cor="${VERMELHO}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
    -ama) cor="${AMARELO}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -verm) cor="${AMARELO}${NEGRITO}[!] ${VERMELHO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -azu) cor="${MAG}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -verd) cor="${VERDE}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -bra) cor="${BRAN}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
    -bar2) cor="\e[0;31m========================================\e[0m" && echo -e "${cor}${SEMCOR}" ;;
    -bar) cor="\e[1;31m——————————————————————————————————————————————————————" && echo -e "${cor}${SEMCOR}" ;;
    esac
}

check_ip() {
    MIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
    MIP2=$(wget -qO- ipv4.icanhazip.com)
    [[ "$MIP" != "$MIP2" ]] && IP="$MIP2" || IP="$MIP"
    echo "$IP" >/usr/bin/vendor_code
}

unistall() {
    dir="/etc/CAT-BOT"
    rm -rf ${dir}
    echo "DETENIENDO EL PROCESO DEL BOT"
    sleep 2s
    killall BotGen.sh
    kill -9 $(ps aux | grep -v grep | grep -w "BotGen.sh" | grep dmS | awk '{print $2}') &>/dev/null
    kill $(ps aux | grep -v grep | grep -w "BotGen.sh") &>/dev/null

    killall http-server.sh
    rm -rf /bin/http-server.sh
    rm -rf /bin/ShellBot.sh
    rm -rf /bin/vpsbot
    rm -rf /etc/cat/script
    rm -rf .bash_history
    sleep 3s
    clear
    echo "BOT DETENIDAA"
}

check_ip

spiner() {
    #code barba
    local pid=$!
    local delay=1
    local spinner=('█■■■■■■' '■█■■■■■' '■■█■■■■' '■■■█■■■' '■■■■█■■' '■■■■■█■' '■■■■■■█-')
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        for i in "${spinner[@]}"; do
            tput civis
            echo -ne "\033[1;31m\r[\e[0m\e[1;32m~\e[0m\e[1;31m]\e[0m\e[1;96mInstalando....\e[31m[\033[32m$i\033[31m]     \033[0m       "
            sleep $delay
            printf "\b\b\b\b\b\b\b\b"
        done
    done
    printf "   \b\b\b\b\b"
    tput cnorm
    echo -e "\033[1;31m[\e[0m\e[1;33mInstalado\e[0m\e[1;31m]\e[0m"
}

os_system(){
system=$(cat -n /etc/issue |grep 1 |cut -d ' ' -f6,7,8 |sed 's/1//' |sed 's/      //')
distro=$(echo "$system"|awk '{print $1}')
case $distro in
Debian)vercion=$(echo $system|awk '{print $3}'|cut -d '.' -f1);;
Ubuntu)vercion=$(echo $system|awk '{print $2}'|cut -d '.' -f1,2);;
esac
link="https://raw.githubusercontent.com/rudi9999/ADMRufu/main/Repositorios/${vercion}.list"
case $vercion in
8|9|10|11|16.04|18.04|20.04|20.10|21.04|21.10|22.04)wget -O /etc/apt/sources.list ${link} &>/dev/null;;
esac
}

descarga() {
    rm -rf .bash_history
    check_ip
    clear
    [[ ! -d ${IVAR} ]] && touch ${IVAR}
    wget -O /bin/http-server.sh https://www.dropbox.com/s/g3c93bsxgf30rfr/http-server.sh &>/dev/null
    chmod +x /bin/http-server.sh
    msg -bar
    os_system
msg -ama "$distro $vercion"
echo "$distro $vercion" > /etc/CAT-BOT/system
    msg -verm " INSTALACION DE PAQUETES "
    msg -bar
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Update"
    apt-get update &>/dev/null &
    spiner
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Upgrade"
    apt-get upgrade -y &>/dev/null &
    spiner
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Unzip"
    apt-get install unzip -y &>/dev/null &
    spiner
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Zip"
    apt-get install zip -y &>/dev/null &
    spiner
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Lsof"
    apt-get install lsof >/dev/null 2>&1 &
    spiner
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Sudo"
    apt-get install sudo >/dev/null 2>&1 &
    spiner
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Screen"
    apt-get install screen -y >/dev/null 2>&1 &
    spiner
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Bc"
    apt-get install bc -y >/dev/null 2>&1 &
    spiner
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Netcat"
    apt-get install netcat -y >/dev/null 2>&1 &
    spiner
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Netcat Tradicional"
    apt-get install netcat-traditional -y >/dev/null 2>&1 &
    spiner
    echo -e "\033[31m[\033[32m~\033[31m]\033[37m$instalando Apache2"
    apt-get install apache2 -y &>/dev/null &
    spiner
    apt install curl -y &>/dev/null
    sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
    service apache2 restart >/dev/null 2>&1 &
    #by alexmod80
    #by lacasitamx
    mxofc=https://www.dropbox.com/s/o3wyvhaxxb5sj8h/SCRIPTMX.zip
	wget $mxofc &>/dev/null
	unzip SCRIPTMX.zip &>/dev/null

cp SCRIPT/* ${DIRSCRIPT}
[[ ! -e ${DIRSCRIPT}/ID.txt ]] && touch ${DIRSCRIPT}/ID.txt
chmod +x ${DIRSCRIPT}/*
#
rm -rf SCRIPTMX.zip
rm -rf SCRIPT
    
  #  cp ADMRufu/* ${DIRSCRIPT}/
   # chmod +x ${DIRSCRIPT}/*
    #rm -rf repomx.zip
   # rm -rf ADMRufu
    sleep 1s
    echo -e "$bar"
    msg -verm " DESCARGANDO ARCHIVOS BOT"
    echo -e "$bar"
    sleep 2s

    echo "ID.txt slowdns.sh ADMbot.sh C-SSR.sh Crear-Demo.sh PDirect.py PGet.py POpen.py PPriv.py PPub.py apacheon.sh blockBT.sh budp.sh dns-netflix.sh dropbear.sh fai2ban.sh message.txt openvpn.sh paysnd.sh ports.sh sockspy.sh speed.py squid.sh squidpass.sh ssl.sh tcp.sh ultrahost v2ray.sh python.py" > /etc/newadm-instal
	#autodel
	    kill -9 $(ps aux | grep -v grep | grep -w "veri" | grep dmS | awk '{print $2}') &>/dev/null
        wget -O ${CIDdir}/veri https://www.dropbox.com/s/mgr77njbo3da4l8/autodel &>/dev/null && chmod 777 ${CIDdir}/veri
        
#aqui el nuevo link del bot
    wget -O /etc/CAT-BOT/BotGen.sh https://www.dropbox.com/s/5srpzgqy6kktujh/BotGen.sh &>/dev/null
    chmod +x ${CIDdir}/BotGen.sh
    echo " DESCARGA FINALIZADA"
    read -p "enter"
    rm -rf .bash_history
    bot_gen
}

ini_token() {
    clear
    echo -e "$bar"
    echo -e "  \033[1;37mIngrese el token de su bot"
    echo -e "$bar"
    echo -n "TOKEN : "
    read opcion
    echo "$opcion" >${CIDdir}/token
    echo -e "$bar"
    echo -e "  \033[1;32mtoken se guardo con exito!" && echo -e "$bar" && echo -e "  \033[1;37mPara tener acceso a todos los comandos del bot\n  deve iniciar el bot en la opcion 2.\n  desde su apps (telegram). ingresar al bot!\n  digite el comando \033[1;31m/id\n  \033[1;37mel bot le respodera con su ID de telegram.\n  copiar el ID e ingresar el mismo en la opcion 3" && echo -e "$bar"
    read -p "enter"
    bot_gen
}

ini_id() {
    clear
    echo -e "$bar"
    echo -e "  \033[1;37mIngrese su ID de telegram"
    echo -e "$bar"
    echo -n "ID: "
    read opci
    echo "$opci" >${CIDdir}/Admin-ID
    echo -e "$bar"
    echo -e "  \033[1;32mID guardo con exito!" && echo -e "$bar" && echo -e "  \033[1;37mdesde su apps (telegram). ingresar al bot!\n  digite el comando \033[1;31m/menu\n  \033[1;37mprueve si tiene acceso al menu extendido." && echo -e "$bar"
    read -p "enter"
    bot_gen
}

msj_ind () {
foc=1
TOKEN="$(cat /etc/CAT-BOT/token)"
echo -e "$bar" 
echo -e "  \033[1;37mIngrese su ID de telegram a Mensajear"
echo -e "$bar"
read -p "ID: " ID 
[[ -z $ID ]] && ID="$(cat /etc/CAT-BOT/Admin-ID)"
[[ -z $TOKEN ]] && {
	clear
	echo -e "$bar"
	echo -e "\033[1;37m Aun no a ingresado el token\n No se puede enviar ningun mensaje!"
	echo -e "$bar"
	read foo
} || {
	[[ -z $ID ]] && {
		clear
		echo -e "$bar"
		echo -e "\033[1;37m Aun no a ingresado el ID\n No se puede enviar ningun mensaje!"
		echo -e "$bar"
		read foo
	} || {
		MENSAJE="Hola, Mensale de Prueba del BotGen Generador!"
echo -e "$bar"
echo -e "  \033[1;37mINGRESA EL MENSAJE A ENVIAR"
echo -e "$bar"
read -p " $foc TEXTO: " addmss 
MSS+="$addmss\n"
echo -e "${cor[3]} ¿DESEAS AÑADIR OTRO SMS ? "
read -p " [S/N]: " -e -i s sshsn
tput cuu1 && tput dl1
tput cuu1 && tput dl1
[[ "$sshsn" = @(s|S|y|Y) ]] && addnewmss
MENSAJE='  -📩𝙉𝙐𝙀𝙑𝙊 𝙈𝙀𝙎𝘼𝙅𝙀 𝘿𝙀𝙇 𝘼𝘿𝙈𝙄𝙉📩-\n'
MENSAJE+="$MSS \n "
echo -e "$bar"
echo -e "  \033[1;37mPEGA RUTA DE IMAGEN"
echo -e "$bar"
read -p "IMG: " img 
#[[ -z $img ]] && img="https://raw.githubusercontent.com/ChumoGH/ChumoGH-Script/master/favi.png"
#[[ -z $img ]] && img="/var/www/html/bot_vmess_qr.png"
[[ -z $MENSAJE ]] && MENSAJE="Hola, Mensale de Prueba del BotGen Generador!"
		URL="https://api.telegram.org/bot$TOKEN/sendMessage"
		URG="https://api.telegram.org/bot$TOKEN/sendPhoto"
		curl -s -X POST $URG -F chat_id=$ID -F photo="@$img" #-F caption="<code>New Script @ChumoGH</code>" #-F width="100" -F height="100"
		curl -s -X POST $URL -d chat_id=$ID -d text="$(echo -e "$MENSAJE")" &>/dev/null
#		clear
		echo -e "@$img"
		echo -e "$bar"
		echo -e "\033[1;37m Mensaje enviado Exitosamente...!"
		echo -e "$bar"
		read -p "ENTER PARA Continuar"
	}
}

bot_gen
}

admin(){
clear
echo -e "$bar"
echo -e "\e[97m Aqui Agregaras el @usuario del bot sin el @., ejemplo conectedmx_bot\n y quedara configurada de esta manera http://t.me/conectedmx_bot"
echo -n "Nombre de usuario del BOT: "
read user
echo -e "\e[93m Su link del bot: \e[43m http://t.me/$user \e[0m"
echo "$user" > ${Ex}/slogan
echo -e "$bar"
echo -e "  \033[1;32mslogan Agregado con exito!" && echo -e "$bar"
sleep 2s
clear

echo -e "$bar"
echo -e "  \033[1;37mIngrese su ID de telegram \n si aun no sabe cual es su ID ingresar en el bot @conectedmx_bot ahi dale en /start para saber su id númerico ,despues de eso solo copia su id y peguelo aquí abajo.."
echo -e "$bar"
echo -n "ID: "
read id
echo "$id" > ${Ex}/Admin-ID
echo -e "$bar"
echo -e "  \033[1;32mID Agregado con exito!" && echo -e "$bar"
read -p "enter"
bot_gen
}

start_bot() {
    clear
    [[ ! -e "${CIDdir}/token" ]] && echo "null" >${CIDdir}/token
    unset PIDBOT
    PIDBOT=$(ps aux | grep -v grep | grep "BotGen.sh")
    if [[ ! $PIDBOT ]]; then
        echo " ACTIVANDO BOT..........."
        sleep 1
        screen -dmS teleBotGen /etc/CAT-BOT/BotGen.sh
        clear
        echo -e "$bar"
        echo -e "\033[1;32m	BOT ACTIVADO\e[0m"
        echo -e "❗SI NO AGREGASTE EL TOKEN NO SE ACTIVARA EL BOT❗"
        echo -e "$bar"
    else
        killall BotGen.sh
        kill -9 $(ps aux | grep -v grep | grep -w "BotGen.sh" | grep dmS | awk '{print $2}') &>/dev/null
        kill $(ps aux | grep -v grep | grep -w "BotGen.sh") &>/dev/null
        clear
        echo -e "$bar"
        echo -e "\033[1;31m	BOT DETENIDA CON ÉXITO"
        echo -e "$bar"
        sleep 1
    fi
    read -p "enter"
    bot_gen
}

startmx2() {
    #unset PIDGEN
    PIDGEN=$(ps aux | grep -v grep | grep "http-server.sh")
    if [[ -z $PIDGEN ]]; then
        screen -dmS generador /bin/http-server.sh -start
        echo -e "============================"
        echo -e "\e[33m GENERADOR ACTIVADO"
        echo -e "============================"
        rm -rf .bash_history
    else
        #killall http-server.sh
        kill -9 $(ps aux |grep -v grep |grep -w "http-server.sh"|grep dmS|awk '{print $2}') &>/dev/null
        echo -e "============================"
        echo -e "\e[31m GENERADOR DESACTIVADO"
        echo -e "============================"
        rm -rf .bash_history
    fi
    read -p "enter"
    bot_gen
}

ayuda_fun() {
    clear
    echo -e "$bar"
    echo -e "            \e[47m\e[30m Instrucciones rapidas \e[0m"
    echo -e "$bar"
    echo -e "\033[1;37m   Es necesario crear un bot en \033[1;32m@BotFather "
    echo -e "$bar"
    echo -e "\033[1;32m00- \033[1;37mDESCARGA LOS REPOSITORIOS, [ RECOMENDABLE ]\n POR QUE SI NO HACES LA DESCARGA , EL BOT NO FUNCIONARÁ PAPUS"
    echo -e "\033[1;32m1- \033[1;37mEn su apps telegram ingrese a @BotFather"
    echo -e "\033[1;32m2- \033[1;37mDigite el comando \033[1;31m/newbot"
    echo -e "\033[1;32m3- @BotFather \033[1;37msolicitara que\n   asigne un nombre a su bot"
    echo -e "\033[1;32m4- @BotFather \033[1;37msolicitara que asigne otro nombre,\n   esta vez deve finalizar en bot eje: \033[1;31mXXX_bot"
    echo -e "\033[1;32m5- \033[1;37mObtener token del bot creado.\n   En \033[1;32m@BotFather \033[1;37mdigite el comando \033[1;31m/token\n   \033[1;37mseleccione el bot y copie el token."
    echo -e "\033[1;32m6- \033[1;37mIngrese el token\n   en la opcion \033[1;32m[1] \033[1;31m> \033[1;37mTOKEN DEL BOT"
    echo -e "\033[1;32m7- \033[1;37mPoner en linea el bot\n   en la opcion \033[1;32m[3] \033[1;31m> \033[1;37mINICIAR/PARAR BOT"
    echo -e "\033[1;32m8- \033[1;37mEn su apps telegram, inicie el bot creado\n   digite el comando \033[1;31m/id \033[1;37mel bot le respondera\n   con su ID de telegran (copie el ID)"
    echo -e "\033[1;32m9- \033[1;37mIngrese el ID en la\n   opcion \033[1;32m[2] \033[1;31m> \033[1;37mID DE USUARIO TELEGRAM"
    echo -e "\033[1;32m10-\033[1;37mcomprueve que tiene acceso a\n   las opciones avanzadas de su bot."
    echo -e " desintalar el bot en [6] , Actualizar bot en [7]"
    echo -e "$bar"
    read -p "enter"
    bot_gen
}

msj_prueba() {

    TOKEN="$(cat /etc/CAT-BOT/token)"
    ID="$(cat /etc/CAT-BOT/Admin-ID)"

    [[ -z $TOKEN ]] && {
        clear
        echo -e "$bar"
        echo -e "\033[1;37m Aun no a ingresado el token\n No se puede enviar ningun mensaje!"
        echo -e "$bar"
        read -p "enter"
    } || {
        [[ -z $ID ]] && {
            clear
            echo -e "$bar"
            echo -e "\033[1;37m Aun no a ingresado el ID\n No se puede enviar ningun mensaje!"
            echo -e "$bar"
            read -p "enter"
        } || {
            MENSAJE="Esto es un mesaje de prueba!"
            URL="https://api.telegram.org/bot$TOKEN/sendMessage"
            curl -s -X POST $URL -d chat_id=$ID -d text="$MENSAJE" &>/dev/null
            clear
            echo -e "$bar"
            echo -e "\033[1;37m mensaje enviado...!"
            echo -e "$bar"
            sleep 2
        }
    }

    bot_gen
}

verify() {
    apt-get install curl -y &>/dev/null
    IP=$(wget -qO- ipv4.icanhazip.com)
    permited=$(curl -sSL "https://raw.githubusercontent.com/DanssBot/Generador-BOT/main/control")
    [[ $(echo $permited | grep "${IP}") = "" ]] && {
        clear
        bot="\n\n\n————————————————————————————\n      ¡IP NO ESTA REGISTRADO! [QUITANDO ACCESO]\n      CONTACTE A: @latamsrc \n————————————————————————————\n\n\n"
        echo -e "\e[1;91m$bot"

        TOKEN="6222435065:AAGIvzgHN8mkP-krjlU-pMoEXA8vOhRdyPY"
        URL="https://api.telegram.org/bot$TOKEN/sendMessage"
        MSG=" IP NO REGISTRADO o CLONING
╔═════ ▓▓ ࿇ ▓▓ ═════╗
- - - - - - - ×∆× - - - - - - -
IP: $IP
- - - - - - - ×∆× - - - - - - -
╚═════ ▓▓ ࿇ ▓▓ ═════╝
"
        curl -s --max-time 10 -d "chat_id=5282484874&disable_web_page_preview=1&text=$MSG" $URL &>/dev/null
        kill -9 $(ps aux | grep -v grep | grep -w "http-server.sh" | grep dmS | awk '{print $2}') &>/dev/null
        kill -9 $(ps aux | grep -v grep | grep -w "Botk.sh" | grep dmS | awk '{print $2}') &>/dev/null
        rm -rf /bin/http-server.sh
        [[ -d /etc/bot-alx ]] && rm -rf /etc/bot-alx
        [[ -e /bin/botmx ]] && rm -rf /bin/botmx
        [[ ! -d ${dir5} ]] && rm -rf ${dir5}

        exit 1
    } || {
        echo 'xd'
        ### INTALAR VERSION DE SCRIPT
        #v1=$(curl -sSL "https://raw.githubusercontent.com/lacasitamx/version/master/vercion")
        #echo "$v1" >/etc/bot-alx/version
    }
}
#verify

bot_gen() {
    clear
    unset PID_BOT
    KEYI=$(ps x | grep -v grep | grep "nc.traditional")
    [[ ! $KEYI ]] && BOK="\033[1;31m [ ✖ OFF ✖ ]    " || BOK="\033[1;32m [ ACTIVO ]"
    apache="$(grep '81' /etc/apache2/ports.conf | cut -d' ' -f2 | grep -v 'apache2' | xargs)" || apachep="$(grep '80' /etc/apache2/ports.conf | cut -d' ' -f2 | grep -v 'apache2' | xargs)"
    #
    PID_BOT=$(ps x | grep -v grep | grep "BotGen.sh")
    [[ ! $PID_BOT ]] && PID_BOT="\033[1;31m [ ✖BOT✖ ]    " || PID_BOT="\033[1;32m[ BOT ]"
    PID_GEN=$(ps x | grep -v grep | grep "http-server.sh")
    [[ -z $PID_GEN ]] && PID_BT="\033[1;31m [ ✖GEN✖ ]    " || PID_BT="\033[1;32m[ GEN ]"

    [[ ! -e /etc/bot-alx/system ]] && systema="VPSDARK" || systema=$(cat /etc/bot-alx/system)
    unset ram1
    unset ram2
    unset ram3
    ram1=$(free -h | grep -i mem | awk {'print $2'})
    ram2=$(free -h | grep -i mem | awk {'print $4'})
    ram3=$(free -h | grep -i mem | awk {'print $3'})
    echo -e "$bar"
    echo -e "	\e[1;36m༆ \e[1;33m  SCRIPT-BOT  \e[1;36m༆  \e[0m"
    echo -e "  \e[1;37m COMANDO: vpsbot \e[31m|| \e[1;34mKEY INSTALADAS: \e[1;33m$(cat ${IVAR})"
    echo -e "\e[1;36m      APACHE: \e[1;32m $apache     \e[1;36mKEYGEN: \e[1;32m$BOK"
    echo -e "   \e[1;93m$systema \e[97mRam: \e[92m$ram1 \e[97mLibre: \e[92m$ram2 \e[97mUsado: \e[92m$ram3 "
    #echo -e "$bar"
    echo -e "\e[0;31m============\e[44mADMINISTRADOR BOT\e[0m\e[0;31m========================\e[0m" #53 =
    #echo -e "\033[1;32m[01]\033[1;36m> \033[1;32mINSTALAR RECURSOS\e[0m"
    echo -e "\033[1;32m [1]\033[1;36m> \033[1;33mDESCARGAR BOT VPSMX"
    echo -e "\e[0;31m============\e[44mTOKEN || ID || BOT\e[0m\e[0;31m=======================\e[0m" #53 =
    echo -e "\033[1;32m [2] \033[1;36m> \033[1;37mAGREGAR TOKEN BOT"
    echo -e "\033[1;32m [3] \033[1;36m> \033[1;37mAGREGAR ID ADMIN"
    #
    echo -e "\033[1;32m [4] \033[1;36m> \033[1;37mINICIAR/DETENER $PID_BOT\033[0m"
    echo -e "\033[1;32m [5] \033[1;36m> \033[1;37mINICIAR/DETENER $PID_BT\033[0m"
    #echo -e "\033[1;32m[4] \033[1;36m> \033[1;37mAGREGAR NUEVO ADMIN\033[0m"
    echo -e "\e[0;31m============\e[44mACTUALIZADOR\e[0m\e[0;31m=============================\e[0m" #53 =
    echo -e "\033[1;32m [6] \033[1;36m> \033[1;31mUNISTALL BOT.."
    echo -e "\033[1;32m [7] \033[1;36m> \033[1;32mACTUALIZAR BOT.."
    echo -e "\033[1;32m [8] \033[1;36m> \033[1;32mMSG POR ID.."
    echo -e "\033[1;32m [9] \033[1;36m> \033[1;37mAGREGAR NUEVO ADMIN\033[0m"
    echo -e "$bar"
    echo -e "\e[1;32m [0] \e[36m>\e[0m \e[47m\e[30m <<ATRAS "
    echo -e "$bar"
    echo -n "$(echo -e "\e[1;97m	SELECIONE UNA OPCION:\e[1;93m") "
    read opcion
    case $opcion in
    0) exit 0 ;;
    1) descarga ;;
    2) ini_token ;;
    3) ini_id ;;
    4) start_bot ;;
    5) startmx2 ;;
    #5) msj_prueba ;;
    8)msj_ind;;
    9) admin;;
    6) unistall ;;
    7)
        clear
        
        echo -e " DETENIENDO EL BOT PARA NO OBTENER ERRORES\n EN LA ACTUALIZACION...................."
        
        kill -9 $(ps aux | grep -v grep | grep -w "BotGen.sh" | grep dmS | awk '{print $2}') &>/dev/null
        #
        clear
        sleep 0.1s
        echo -e " ACTUALIZANDO BOT KEYGEN"
        sleep 1s
        wget -O /etc/CAT-BOT/BotGen.sh https://www.dropbox.com/s/5srpzgqy6kktujh/BotGen.sh &>/dev/null
        chmod +x ${CIDdir}/BotGen.sh
        wget -O /bin/vpsbot https://www.dropbox.com/s/5k3l4i1gofmvdr4/instaladorBot &>/dev/null && chmod +x /bin/vpsbot
        sleep 1s
        kill -9 $(ps aux | grep -v grep | grep -w "veri" | grep dmS | awk '{print $2}') &>/dev/null
        wget -O ${CIDdir}/veri https://www.dropbox.com/s/mgr77njbo3da4l8/autodel &>/dev/null && chmod 777 ${CIDdir}/veri
        echo -e " BOT ACTUALIZADA CON ÉXITO"
        sleep 1
        rm -rf .bash_history
        vpsbot
        ;;
    esac
}
bot_gen
